🪄 upgrade to ndk-r23c
Had to upgrade to ndk-r23c because builds with ndk-r22 doesn't seem to
work anymore, here's the error message I encountered:

```
RUSTFLAGS='-C link-arg=-s' cargo ndk -t armeabi-v7a -t arm64-v8a -t x86 -t x86_64 -o ../android/arti/src/main/jniLibs build --release
    Building armeabi-v7a (armv7-linux-androideabi)
error: NDK versions less than r23 are not supported. Install an up-to-date version of the NDK.
```